import { HERO_MESSAGES, type HeroMessage } from './heroArt.generated'

// The rotating messages (generated by `npm run generate:hero-art`); the first is the owner's name.
export { HERO_MESSAGES, type HeroMessage }

// Room to reserve so rotating between messages never shifts the page.
export const HERO_MAX_WIDTH = Math.max(...HERO_MESSAGES.map((m) => m.rows[0].length))
export const HERO_MAX_HEIGHT = Math.max(...HERO_MESSAGES.map((m) => m.rows.length))

// Each glyph of a message as its rows of text (one string per art row).
export function heroGlyphRows(message: HeroMessage): string[][] {
  return message.glyphColumns.map(([start, end]) => message.rows.map((row) => row.slice(start, end)))
}
